---
title: "Table Schema"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{table-schema}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Schema

`schema` is required and must follow the [Table Schema](https://specs.frictionlessdata.io/table-schema/) specification. It can either be a JSON object or a path or URL referencing a JSON object.

- Field `name`s are used as column headers.
- Field `type`s are use as column types (see further).
- [`missingValues`](https://specs.frictionlessdata.io/table-schema/#missing-values)
  are used to interpret as `NA`, with `""` as default.

## Field types

Field `type` is used to set the column type, as follows:

- [string](https://specs.frictionlessdata.io/table-schema/#string) as `character`; or `factor` when `enum` is present. `format` is ignored.
- [number](https://specs.frictionlessdata.io/table-schema/#number) as `double`; or `factor` when `enum` is present. Use `bareNumber: false` to ignore whitespace and non-numeric characters. `decimalChar` (`.` by default) and `groupChar` (undefined by default) can be defined, but the most occurring value will be used as a global value for all number fields of that resource.
- [integer](https://specs.frictionlessdata.io/table-schema/#integer) as `double` (not integer, to avoid issues with big numbers); or `factor` when `enum` is present. Use `bareNumber: false` to ignore whitespace and non-numeric characters.
- [boolean](https://specs.frictionlessdata.io/table-schema/#boolean) as `logical`. Non-default `trueValues/falseValues` are not supported.
- [object](https://specs.frictionlessdata.io/table-schema/#object) as `character`.
- [array](https://specs.frictionlessdata.io/table-schema/#array) as `character`.
- [date](https://specs.frictionlessdata.io/table-schema/#date) as `date`. Supports `format`, with values `default` (ISO date), `any` (guess `ymd`) and [Python/C strptime](https://docs.python.org/2/library/datetime.html#strftime-strptime-behavior) patterns, such as `%a, %d %B %Y` for `Sat, 23 November 2013`. `%x` is `%m/%d/%y`. `%j`, `%U`, `%w` and `%W` are not supported.
- [time](https://specs.frictionlessdata.io/table-schema/#time) as `hms::hms()`. Supports `format`, with values `default` (ISO time), `any` (guess `hms`) and [Python/C strptime](https://docs.python.org/2/library/datetime.html#strftime-strptime-behavior) patterns, such as `%I%p%M:%S.%f%z` for `8AM30:00.300+0200`.
- [datetime](https://specs.frictionlessdata.io/table-schema/#datetime) as `POSIXct`. Supports `format`, with values `default` (ISO datetime), `any` (ISO datetime) and the same patterns as for `date` and `time`. `%c` is not supported.
- [year](https://specs.frictionlessdata.io/table-schema/#year) as `date`, with `01` for month and day.
- [yearmonth](https://specs.frictionlessdata.io/table-schema/#yearmonth) as `date`, with `01` for day.
- [duration](https://specs.frictionlessdata.io/table-schema/#duration) as `character`. Can be parsed afterwards with `lubridate::duration()`.
- [geopoint](https://specs.frictionlessdata.io/table-schema/#geopoint) as `character`.
- [geojson](https://specs.frictionlessdata.io/table-schema/#geojson) as `character`.
- [any](https://specs.frictionlessdata.io/table-schema/#any) as `character`.
- Any other value is not allowed.
- Type is guessed if not provided.
